export const GET_PETS_REQUEST = 'GET_PETS_REQUEST';
export const GET_PETS_SUCCESS = 'GET_PETS_SUCCESS';
export const GET_PETS_ERROR = 'GET_PETS_ERROR';

export const CREATE_PET_REQUEST = 'CREATE_PET_REQUEST';
export const CREATE_PET_SUCCESS = 'CREATE_PET_SUCCESS';
export const CREATE_PET_ERROR = 'CREATE_PET_ERROR';

export const DELETE_PET_REQUEST = 'DELETE_PET_REQUEST';
export const DELETE_PET_SUCCESS = 'DELETE_PET_SUCCESS';
export const DELETE_PET_ERROR = 'DELETE_PET_ERROR';

export const GET_PET_REQUEST = 'GET_PET_REQUEST';
export const GET_PET_SUCCESS = 'GET_PET_SUCCESS';
export const GET_PET_ERROR = 'GET_PET_ERROR';

export const UPDATE_PET_REQUEST = 'UPDATE_PET_REQUEST';
export const UPDATE_PET_SUCCESS = 'UPDATE_PET_SUCCESS';
export const UPDATE_PET_ERROR = 'UPDATE_PET_ERROR';
