export const CHECK_USERNAME_AVAILABILITY_REQUEST = 'CHECK_USERNAME_AVAILABILITY_REQUEST';
export const CHECK_USERNAME_AVAILABILITY_SUCCESS = 'CHECK_USERNAME_AVAILABILITY_SUCCESS';
export const CHECK_USERNAME_AVAILABILITY_ERROR = 'CHECK_USERNAME_AVAILABILITY_ERROR';
