export const CHECK_USERNAME_AVAILABILITY_REQUEST = 'CHECK_USERNAME_AVAILABILITY_REQUEST';
export const CHECK_USERNAME_AVAILABILITY_SUCCESS = 'CHECK_USERNAME_AVAILABILITY_SUCCESS';
export const CHECK_USERNAME_AVAILABILITY_ERROR = 'CHECK_USERNAME_AVAILABILITY_ERROR';

export const VALIDATE_USERNAME_SUCCESS = 'VALIDATE_USERNAME_SUCCESS';
export const VALIDATE_USERNAME_ERROR = 'VALIDATE_USERNAME_ERROR';

export const VALIDATE_PASSWORD_SUCCESS = 'VALIDATE_PASSWORD_SUCCESS';
export const VALIDATE_PASSWORD_ERROR = 'VALIDATE_PASSWORD_ERROR';

export const VALIDATE_PET_NAME_SUCCESS = 'VALIDATE_PET_NAME_SUCCESS';
export const VALIDATE_PET_NAME_ERROR = 'VALIDATE_PET_NAME_ERROR';

export const VALIDATE_PET_BIRTHDAY_SUCCESS = 'VALIDATE_PET_BIRTHDAY_SUCCESS';
export const VALIDATE_PET_BIRTHDAY_ERROR = 'VALIDATE_PET_BIRTHDAY_ERROR';

export const VALIDATE_PET_SPECIES_SUCCESS = 'VALIDATE_PET_SPECIES_SUCCESS';
export const VALIDATE_PET_SPECIES_ERROR = 'VALIDATE_PET_SPECIES_ERROR';

export const VALIDATE_PET_LAT_SUCCESS = 'VALIDATE_PET_LAT_SUCCESS';
export const VALIDATE_PET_LAT_ERROR = 'VALIDATE_PET_LAT_ERROR';

export const VALIDATE_PET_LNG_SUCCESS = 'VALIDATE_PET_LNG_SUCCESS';
export const VALIDATE_PET_LNG_ERROR = 'VALIDATE_PET_LNG_ERROR';
