export const CHECK_USERNAME_AVAILABILITY_REQUEST = 'CHECK_USERNAME_AVAILABILITY_REQUEST';
export const CHECK_USERNAME_AVAILABILITY_SUCCESS = 'CHECK_USERNAME_AVAILABILITY_SUCCESS';
export const CHECK_USERNAME_AVAILABILITY_ERROR = 'CHECK_USERNAME_AVAILABILITY_ERROR';

export const VALIDATE_USERNAME_SUCCESS = 'VALIDATE_USERNAME_SUCCESS';
export const VALIDATE_USERNAME_ERROR = 'VALIDATE_USERNAME_ERROR';

export const VALIDATE_PASSWORD_SUCCESS = 'VALIDATE_PASSWORD_SUCCESS';
export const VALIDATE_PASSWORD_ERROR = 'VALIDATE_PASSWORD_ERROR';

export const VALIDATE_PET_FORM_ERROR = 'VALIDATE_PET_FORM_ERROR';
export const VALIDATE_PET_FORM_SUCCESS = 'VALIDATE_PET_FORM_SUCCESS';

export const RESET_PET_FORM = 'RESET_PET_FORM';

export const TOGGLE_DATEPICKER_VISIBILITY = 'TOGGLE_DATEPICKER_VISIBILITY';

export const PET_NAME_CHANGE = 'PET_NAME_CHANGE';

export const PET_FORM_CHANGE = 'PET_FORM_CHANGE';

export const INIT_PET_FORM = 'INIT_PET_FORM';
