export const CHECK_USERNAME_AVAILABILITY_REQUEST = 'CHECK_USERNAME_AVAILABILITY_REQUEST';
export const CHECK_USERNAME_AVAILABILITY_SUCCESS = 'CHECK_USERNAME_AVAILABILITY_SUCCESS';
export const CHECK_USERNAME_AVAILABILITY_ERROR = 'CHECK_USERNAME_AVAILABILITY_ERROR';

export const VALIDATE_USERNAME_SUCCESS = 'VALIDATE_USERNAME_SUCCESS';
export const VALIDATE_USERNAME_ERROR = 'VALIDATE_USERNAME_ERROR';

export const VALIDATE_PASSWORD_SUCCESS = 'VALIDATE_PASSWORD_SUCCESS';
export const VALIDATE_PASSWORD_ERROR = 'VALIDATE_PASSWORD_ERROR';
